# variables in header
{}

# variables in path
image_id:
  description: |
    Image ID stored through the image API. Typically
    a UUID.
  in: path
  required: false
  type: string
owner_id:
  description: |
    Owner ID, which is the tenant ID.
  in: path
  required: false
  type: string

# variables in query
changes-since:
  description: |
    Filters the image list to those images that have
    changed since a time stamp value.
  in: query
  required: false
  type: string
container_format_1:
  description: |
    Filters the image list by a container format. A
    valid value is ``aki``, ``ami``, ``ari``, ``bare``, ``docker``,
    ``ova``, or ``ovf``.
  in: query
  required: false
  type: string
disk_format_1:
  description: |
    Filters the image list by a disk format. A valid
    value is ``aki``, ``ami``, ``ari``, ``iso``, ``qcow2``, ``raw``,
    ``vhd``, ``vdi``, or ``vmdk``.
  in: query
  required: false
  type: string
name_1:
  description: |
    Filters the image list by an image name, in
    string format.
  in: query
  required: false
  type: string
size_max:
  description: |
    Filters the image list by a maximum image size,
    in bytes.
  in: query
  required: false
  type: string
size_min:
  description: |
    Filters the image list by a minimum image size,
    in bytes.
  in: query
  required: false
  type: string
status:
  description: |
    Filters the image list by a status. A valid value
    is ``queued``, ``saving``, ``active``, ``killed``, ``deleted``, or
    ``pending_delete``.
  in: query
  required: false
  type: string

# variables in body
can_share:
  description: |
    Indicates whether the owner is authorized to
    share the image.  If the owner can share the image, this value is
    ``true``. Otherwise, this value is ``false``.  Specify the owner
    ID, which is the tenant ID, is in the request URI.
  in: body
  required: true
  type: boolean
container_format:
  description: |
    A container format defines the file format of the
    file that contains the image and metadata about the actual VM.
    For a VM image with a ``bare`` container format, the image is a
    blob of unstructured data.  You can set the container format to
    one of these values:  - ``aki``    Amazon kernel image.  - ``ami``
    Amazon machine image.  - ``ari``    Amazon ramdisk image.  -
    ``bare``    No container or metadata envelope for the image.  -
    ``docker``    Docker tar archive of the container filesystem.  -
    ``ova``    OVA container format.  - ``ovf``    OVF container
    format.
  in: body
  required: true
  type: string
createImage:
  description: |
    Local file path where the image is stored.
  in: body
  required: false
  type: string
disk_format:
  description: |
    The disk format of a VM image is the format of
    the underlying disk image. Virtual appliance vendors have
    different formats for laying out the information contained in a VM
    disk image.  You can set the disk format for your image to one of
    these values:  - ``aki``    An Amazon kernel image.  - ``ami``
    An Amazon machine image.  - ``ari``    An Amazon ramdisk image.  -
    ``iso``    An archive format for the data contents of an optical
    disc, such   as CDROM.  - ``qcow2``    Supported by the QEMU
    emulator that can expand dynamically and   supports Copy on Write.
    - ``raw``    Unstructured disk image format.  - ``vhd``    VHD
    disk format, a common disk format used by VM monitors from
    VMWare, Xen, Microsoft, VirtualBox, and others.  - ``vdi``
    Supported by VirtualBox VM monitor and the QEMU emulator.  -
    ``vmdk``    A common disk format that supported by many VM
    monitors.
  in: body
  required: true
  type: string
images:
  description: |
    A list of ``image`` objects.
  in: body
  required: true
  type: array
location:
  description: |
    A URI location for the image.
  format: uri
  in: body
  required: true
  type: string
location_1:
  format: uri
  in: body
  required: true
  type: string
member_id:
  description: |
    The UUID of the member with which an image is
    shared.
  in: body
  required: true
  type: string
memberships:
  in: body
  required: true
  type: string
name:
  description: |
    Name for the image. Note that the name of an
    image is not unique to an Image service node. The API cannot
    expect users to know the names of images that other users own.
  in: body
  required: true
  type: string
next:
  description: |
    Show the next item in the list.
  format: uri
  in: body
  required: false
  type: string
previous:
  description: |
    Show the previous item in the list.
  format: uri
  in: body
  required: false
  type: string
size:
  description: |
    The size of the image, in bytes.
  in: body
  required: true
  type: string
uri:
  description: |
    The exact location needed to get the metadata for
    the image.
  in: body
  required: true
  type: string

