# variables in header
{}

# variables in path
network_id_1:
  description: |
    The UUID of the network.
  in: path
  required: false
  type: string
port_id:
  description: |
    The UUID of the port.
  in: path
  required: false
  type: string
subnet_id_2:
  description: |
    The UUID of the subnet.
  in: path
  required: false
  type: string

# variables in query
{}

# variables in body
admin_state_up:
  description: |
    The administrative state of the network, which is
    up (``true``) or down (``false``).
  in: body
  required: false
  type: boolean
admin_state_up_1:
  description: |
    The administrative status of the port, which is
    up (``true``) or down (``false``).
  in: body
  required: false
  type: boolean
admin_state_up_2:
  description: |
    The administrative state of the network, which is
    up (``true``) or down (``false``).
  in: body
  required: true
  type: boolean
admin_state_up_3:
  description: |
    The administrative state of the port, which is up
    (``true``) or down (``false``).
  in: body
  required: true
  type: boolean
allowed_address_pairs:
  description: |
    A set of zero or more allowed address pairs. An
    address pair contains an IP address and MAC address.
  in: body
  required: false
  type: array
allowed_address_pairs_1:
  description: |
    A set of zero or more allowed address pairs. An
    address pair consists of an IP address and MAC address.
  in: body
  required: true
  type: array
availability_zone_hints:
  description: |
    The availability zone candidate for the network.
  in: body
  required: true
  type: array
availability_zones:
  description: |
    The availability zone for the network.
  in: body
  required: true
  type: array
changed_at:
  description: |
    Time at which the network has been created.
  in: body
  required: true
  type: string
created_at:
  description: |
    Time at which port has been created.
  in: body
  required: true
  type: string
default:
  description: |
    Defines whether the provider is the default for
    the service type. If this value is ``true``, the provider is the
    default. If this value is ``false``, the provider is not the
    default.
  in: body
  required: true
  type: boolean
device_id:
  description: |
    The UUID of the device that uses this port. For
    example, a virtual server.
  in: body
  required: false
  type: string
device_id_1:
  description: |
    The UUID of the device that uses this port. For
    example, a virtual server.
  in: body
  required: true
  type: string
device_owner:
  description: |
    The UUID of the entity that uses this port. For
    example, a DHCP agent.
  in: body
  required: false
  type: string
device_owner_1:
  description: |
    The UUID of the entity that uses this port. For
    example, a DHCP agent.
  in: body
  required: true
  type: string
extra_dhcp_opts:
  description: |
    A set of zero or more extra DHCP option pairs. An
    option pair consists of an option value and name.
  in: body
  required: true
  type: array
fixed_ips:
  description: |
    If you specify only a subnet UUID, OpenStack
    Networking allocates an available IP from that subnet to the port.
    If you specify both a subnet UUID and an IP address, OpenStack
    Networking tries to allocate the address to the port.
  in: body
  required: false
  type: array
fixed_ips_1:
  description: |
    The IP addresses for the port. Includes the IP
    address and UUID of the subnet.
  in: body
  required: true
  type: array
id:
  description: |
    The UUID of the network.
  in: body
  required: true
  type: string
id_1:
  description: |
    The UUID of the port.
  in: body
  required: true
  type: string
ip_address:
  description: |
    The IP address of an allowed address pair.
  in: body
  required: false
  type: string
ip_address_1:
  description: |
    The fixed IP address of the port.
  in: body
  required: true
  type: string
location:
  description: |
    Full URL to a service or server.
  format: uri
  in: body
  required: true
  type: string
mac_address:
  description: |
    The MAC address of an allowed address pair.
  in: body
  required: false
  type: string
mac_address_1:
  description: |
    The MAC address.
  in: body
  required: true
  type: string
mtu:
  description: |
    The MTU of a network resource.
  in: body
  required: true
  type: integer
name:
  description: |
    The network name.
  in: body
  required: false
  type: string
name_1:
  description: |
    A symbolic name for the port.
  in: body
  required: false
  type: string
name_2:
  description: |
    The network name.
  in: body
  required: true
  type: string
name_3:
  description: |
    The port name.
  in: body
  required: true
  type: string
name_4:
  description: |
    User-facing provider name.
  in: body
  required: true
  type: string
network:
  description: |
    A ``network`` object.
  in: body
  required: true
  type: object
network_id:
  description: |
    The UUID of the network.
  in: body
  required: true
  type: string
network_id_2:
  description: |
    The UUID of the attached network.
  in: body
  required: true
  type: string
networks:
  description: |
    A list of ``network`` objects.
  in: body
  required: true
  type: array
opt_name:
  description: |
    The extra DHCP option name.
  in: body
  required: false
  type: string
opt_name_1:
  description: |
    The extra DHCP option name.
  in: body
  required: true
  type: string
opt_value:
  description: |
    The extra DHCP option value.
  in: body
  required: false
  type: string
opt_value_1:
  description: |
    The extra DHCP option value.
  in: body
  required: true
  type: string
port:
  description: |
    A ``port`` object.
  in: body
  required: true
  type: object
port_security_enabled:
  description: |
    The port security status. A valid value is
    enabled (``true``) or disabled (``false``).
  in: body
  required: false
  type: boolean
port_security_enabled_1:
  description: |
    The port security status. The status is enabled
    (``true``) or disabled (``false``).
  in: body
  required: true
  type: boolean
ports:
  description: |
    A list of ``port`` objects.
  in: body
  required: true
  type: array
router:external:
  description: |
    Indicates whether this network is externally
    accessible.
  in: body
  required: false
  type: boolean
router:external_1:
  description: |
    Indicates whether this network is externally
    accessible.
  in: body
  required: true
  type: boolean
security_groups:
  description: |
    One or more security group UUIDs.
  in: body
  required: false
  type: array
security_groups_1:
  description: |
    The UUIDs of any attached security groups.
  in: body
  required: true
  type: array
service_providers:
  description: |
    A list of ``service_provider`` objects.
  in: body
  required: true
  type: array
service_type:
  description: |
    The service type, which is ``CORE``, ``DUMMY``,
    ``FIREWALL``, ``FLAVORS``, ``L3_ROUTER_NAT``, ``LOADBALANCER``,
    ``LOADBALANCERV2``, ``METERING``, ``QOS``, or ``VPN``.
  in: body
  required: true
  type: string
shared:
  description: |
    Admin-only. Indicates whether this network is
    shared across all tenants.
  in: body
  required: false
  type: boolean
shared_1:
  description: |
    Indicates whether this network is shared across
    all tenants. By default, only administrative users can change this
    value.
  in: body
  required: true
  type: boolean
status:
  description: |
    The network status.
  in: body
  required: true
  type: string
status_1:
  description: |
    The port status. Value is ``ACTIVE`` or ``DOWN``.
  in: body
  required: true
  type: string
subnet_id:
  description: |
    If you specify only a subnet UUID, OpenStack
    Networking allocates an available IP from that subnet to the port.
    If you specify both a subnet UUID and an IP address, OpenStack
    Networking tries to allocate the address to the port.
  in: body
  required: false
  type: string
subnet_id_1:
  description: |
    The UUID of the subnet to which the port is
    attached.
  in: body
  required: true
  type: string
subnets:
  description: |
    The associated subnets.
  in: body
  required: true
  type: array
tenant_id:
  description: |
    The UUID of the tenant who owns the network. Only
    administrative users can specify a tenant UUID other than their
    own. You cannot change this value through authorization policies.
  in: body
  required: false
  type: string
tenant_id_1:
  description: |
    The UUID of the tenant.
  in: body
  required: true
  type: string
tenant_id_2:
  description: |
    The UUID of the tenant who owns the network. Only
    administrative users can specify a tenant UUID other than their
    own.
  in: body
  required: true
  type: string
updated_at:
  description: |
    Time at which port has been updated.
  in: body
  required: true
  type: string
updated_at_1:
  description: |
    Time at which the network has been updated.
  in: body
  required: true
  type: string

